# Generated by Django 4.2 on 2025-06-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_document_link_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Exam', 'Exam'), ('TD', 'TD'), ('DS', 'DS'), ('TP', 'TP')], default='TD', help_text='Type of document (Exam, TD, DS, TP)', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.subject'),
        ),
    ]
