# Generated by Django 4.2 on 2025-06-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_document_type_alter_document_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='corrected_file',
            field=models.FileField(blank=True, help_text='Upload a corrected version file or provide a corrected link below.', null=True, upload_to='documents/corrected/'),
        ),
        migrations.AddField(
            model_name='document',
            name='corrected_link',
            field=models.URLField(blank=True, help_text='Paste a link to a corrected version (e.g., Google Drive)', null=True),
        ),
    ]
