# Generated by Django 4.2 on 2025-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_document_corrected_file_document_corrected_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='has_correction',
            field=models.BooleanField(default=False, help_text='Check if a corrected version is provided.'),
        ),
    ]
