# Generated by Django 4.2 on 2025-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_document_has_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='corrected_file',
            field=models.FileField(blank=True, help_text='Upload a corrected file if available.', null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='corrected_link',
            field=models.URLField(blank=True, help_text='Paste a link to a corrected document if available.', null=True),
        ),
    ]
