# Generated by Django 4.2 on 2025-06-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_document_corrected_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('Exam', 'Exam'), ('DS', 'DS'), ('TP', 'TP'), ('Resume', 'Resume'), ('Other', 'Other')], default='TD', help_text='Type of document (Exam, TD, DS, TP)', max_length=10),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.subject')),
            ],
        ),
    ]
