# Generated by Django 4.2 on 2025-06-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_class_subject_subject_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.class'),
        ),
    ]
